apiVersion: v1
kind: Service
metadata:
  name: advertising-sales-service
spec:
  type: NodePort
  selector:
    app: advertising-sales-api
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30008
