name: Deploy to Kind Kubernetes

on:
  workflow_run:
    workflows: ["Publish Docker Image"]
    types:
      - completed

  workflow_dispatch:

jobs:
  deploy-kubernetes:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    runs-on: [self-hosted, docker]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Pull Latest Docker Image
        run: |
          docker pull mohamedabdelnasser414/advertising-sales-api:latest

      - name: Apply Kubernetes Deployment
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      - name: Check Kubernetes Resources
        run: |
          kubectl get deployments
          kubectl get pods
          kubectl get services